# Generated by Django 5.2.8 on 2025-11-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_participant_invoice_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
