# Generated by Django 5.2.8 on 2025-11-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_userprofile_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('credit_card', 'Credit Card'), ('cash', 'Cash'), ('other', 'Other')], max_length=50, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_notes',
            field=models.TextField(blank=True, verbose_name='Payment Notes'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='invoices/proof_of_payment/', verbose_name='Proof of Payment'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('under_review', 'Under Review'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
